### ISSUE TITLE
Add stats to Pokemon class

### ISSUE THREAD

**Issue by MercuryExalted** [CL-mullins/Pokemon-Battler#4]
Similar to how Pokemon works, I want each Pokemon to either have stats or be instantiated with stats. I want the stats to vary between various versions of the Pokémon.

_this seems difficult, but its really all to test my abilities _

**Comment by vmdhhh** [comment]
@CL-mullins I would like to help if it's ok.
Please let me know the details.

**Comment by MercuryExalted** [comment]
@vmdhhh I just need base stats to be an instance variable for the Pokemon class. I also want them to be able to be effected by items and scaling by level.
![image](https://user-images.githubusercontent.com/69275653/101074886-25a59400-3556-11eb-8480-6cebb1e382b1.jpeg)
However, I don't like the idea of passing it as an argument every time a Pokemon is initialized, so if you can find a way to integrate that, that would be cool.

**Comment by vmdhhh** [comment]
@CL-mullins 
I could think of one way, we can have a range for each stat and generate stats randomly from that range for each pokemon when it's initialized.
Is this what you desire?

**Comment by MercuryExalted** [comment]
Yeah that sounds good, i just want it to be relative per level
